# configuration file for role
role = "timestamp"
key_type = "ed25519"
private_key = "-----BEGIN PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEILLca+FcD5Rf/DN4hCcuDgNte07q6SclZ2QRqJ1goZrP\n-----END PRIVATE KEY-----"
public_key = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAFykzm7aHONpKpdZIyyE48kBXl6SS2NdyafGsI0+4zlA=\n-----END PUBLIC KEY-----"

# hash configuration
[hash]
bufsize = 65536    # default is 8kb 
function = "sha256"

[signature]
algorithm = "eddsa"   

