[signatures]
keyid = "publickey"
sig = "signature of signed portion"

[signed]
_type = "snapshot"
spec_version = "0.0.1"
version = "0.0.1"
expires = ""

[signed.targets.name_of_tagets_metadata_file]
hash = "hash of tagets metadata file"
version = "" # to be implemented

[signed.targets.name_of_targets_metadata_file]
hash = "hash of targets metadata file"
version = "" # to be implemented
