[signatures]
keyid = "publickey"
sig = "signature of signed portion"

[signed]
_type = "timestamp"
spec_version = "0.0.1"
version = "0.0.1"
expires = ""
image_name = "name of image"
image_url = "url of latest image"
image_size = "size of image"
image_hash = "hash of image"
image_version = "version of latest image"
snapshot_metadata_file_hash = "url of latest image metadata" #snapshot metadata 

