[signatures]
keyid = "publickey"
sig = "signature of signed portion"

[signed]
_type = "timestamp"
spec_version = "0.0.1"
version = "0.0.1"
expires = ""
bufsize = 64372
snapshot_metadata_file_hash = "url of latest image metadata" #snapshot metadata 

