# configuration file for role
role = "timestamp"
key_type = "ed25519"
private_key = "private key in pem format"
public_key = "public key in pem format"

# hash configuration
[hash]
bufsize = 65536    # default is 8kb 
function = "hash function to be used"

[signature]
algorithm = "eddsa"   

